### ISSUE TITLE
Treat Rate Limit via Request Throttling

### ISSUE THREAD

**Issue by malukenho** [codelicia/trineforce#6]
Nowadays we don't treat cases of *Request Throttling*, which Salesforce sends to us out of the box in every REST response. We should be able to trigger specific exceptions for these cases of rate limit. 

`RequestThrottlingException`
`RequestThrottlingException::create()`
`RequestThrottlingException::copy()`

https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/headers_api_usage.htm

**Comment by malukenho** [comment]
@all-contributors please add @malukenho

**Comment by malukenho** [comment]
@all-contributors please add @malukenho for code

**Comment by malukenho** [comment]
@all-contributors please add @malukenho for maintenance
@all-contributors please add @EHER  for maintenance

**Comment by malukenho** [comment]
@all-contributors please add @malukenho for maintenance

**Comment by malukenho** [comment]
@all-contributors please add @echevalaz  for bug reports and ideas

**Comment by EHER** [comment]
@echevalaz do you know how can we have an org to work on this kind of issue?
