### ISSUE TITLE
Fix examples in readme.md

### ISSUE THREAD

**Issue by rodrigoaguilera** [codelicia/trineforce#73]
I have been trying to use the examples to make my own queries but I haven't been able to use them verbatim.

If I try 
```
        $stmt = $this->connection->createQueryBuilder()
            ->select(['AccountId', 'Name'])
            ->from('Contact')
            ->where('AccountId = :id')
            ->setParameter('id', '0013Y00002ZZLOzQAP')
            ->setMaxResults(1);
```

I get the following invalid SOQL query
```
SELECT AccountId, Name FROM Contact WHERE AccountId = :'0013Y00002ZZLOzQAP' LIMIT 1
```
Notice the colon before the AccountId string.
To get a proper SOQL query I need to use `->setParameter(':id', '0013Y00002ZZLOzQAP')` with the colon.

Also trying to use positional parameters it seems like the index starts at 1 for positional parameter because of the use of 
`Doctrine\DBAL\Driver\OCI8\ConvertPositionalToNamedPlaceholders;` in the SoqlStatement class.
 
When I read the docs the positional parameters usually start at `0` but not for this driver.
https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/query-builder.html

Is there a reason why there is a custom logic in this driver around parameters?

I'm not proposing a change in the readme yet because first I want to clarify the reasoning behind the current code.

Congratulations on a great piece of software.

**Comment by malukenho** [comment]
Fixed on branch `2.x.x`
